name: Docker image

on:
  push:
    branches:
    - master
    paths:
    - 'scripts/Dockerfile'
    - 'scripts/properties.sh'
    - 'scripts/setup-android-sdk.sh'
    - 'scripts/setup-ubuntu.sh'
    - 'scripts/setup-cgct.sh'
  schedule:
    - cron:  '0 2 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Build
      run: |
        cd ./scripts
        docker build --tag cloudorz/package-builder:latest .
        docker build --tag termux/package-builder-cgct:latest --file Dockerfile.cgct .
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: cloudorz
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Push
      run: |
        # ghcr.io seem to be unstable sometimes. It may suddenly drop connection
        # during docker push when some layers are already uploaded. The workaround
        # is to retry again 1 or 2 more times.
        for image in package-builder package-builder-cgct; do
          for t in 1 2 3; do
            if docker push "${registry}cloudorz/${image}:latest"; then
              break
            else
              if [ "$t" = "3" ]; then
                echo "Giving up after 3 attempts"
                exit 1
              fi
              sleep 20
            fi
          done
        done
